name = "do-worker"
main = "src/index.ts"
compatibility_date = "2024-04-05"


kv_namespaces = [
  { binding = "EXAMPLE_KV", id = "a-shared-id" }
]

[[durable_objects.bindings]]
name = "MY_DO"
class_name = "DurableObjectClass"
